version: '3.9'
services:
  front:
    build:
      context: ./front
      dockerfile: Dockerfile
    volumes:
      - ./front:/usr/src/front # ローカルをコンテナ内にマウント
    ports:
      - "3000:3000"
    stdin_open: true 
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=development
    volumes:
      - ./api:/usr/src/app